-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Player CASCADE;

DROP TABLE IF EXISTS Area CASCADE;

DROP TABLE IF EXISTS Tag CASCADE;

DROP TABLE IF EXISTS Topic CASCADE;

DROP TABLE IF EXISTS Message CASCADE;

DROP TABLE IF EXISTS Topictag CASCADE;
